schema_version: 1

context:
  name: azure-synapse-accesscontrol
  version: 0.5.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-synapse-accesscontrol-${{ version }}.zip
  sha256: 835e324a2072a8f824246447f049c84493bd43a1f6bac4b914e78c090894bb04

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1,<2.0
    - azure-core >=1.6.0,<2.0
    - msrest >=0.5.0

tests:
  - python:
      imports:
        - azure.synapse.accesscontrol
        - azure.synapse.accesscontrol.aio
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Microsoft Azure Synapse AccessControl Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
